### ISSUE TITLE
Ionic Plugin Add

### ISSUE THREAD

**Issue by oddoye-david** [flavordaaave/ionic-better-structure#1]
Very good project.

How do i add plugins? 

Keep getting this error "Current working directory is not a Cordova-based project."

**Comment by davidruisinger** [comment]
Hey,
it's because the "www" folder is missing per default. Just add an empty folder "www" to the root of this project or just run

```
gulp build
```

which will initially create the "www" folder and build the project.

I'll add the "www" folder per default with my next update to this project.
THX for the feedback!
