### ISSUE TITLE
JSCS doesn't output formatting errors

### ISSUE THREAD

**Issue by nahankid** [flavordaaave/ionic-better-structure#3]
Hi,

Thanks for the structure, it's pretty cool. However, I can't get JSCS to output formatting errors. Same file, with poorly formatted code, outputs errors when used with John Papa's HotTowel app. 

Any idea? 

Thanks,
SG

**Comment by davidruisinger** [comment]
Could you give me a JS example? I just did a basic test by removing the semicolon in line 12 of the `dash.controller.js`file and `gulp vet` is correctly showing me the error:

```
[13:01:04] Starting 'vet'...
[13:01:04] Analyzing source with JSHint and JSCS

src/app/dash/dash.controller.js
  line 12  col 22  Missing semicolon.  (W033)

  ⚠  1 warning

[13:01:06] Finished 'vet' after 2.06 s
```

**Comment by nahankid** [comment]
You’re absolutely right. Semicolons are reported. I was talking about formatting errors like we see in Papa John’s structure.

[20:36:19] Using gulpfile ~/code/hello/gulpfile.js

[20:36:19] Starting 'vet'...

[20:36:19] Analyzing source with JSHint and JSCS

[20:36:21] 'vet' errored after 2.24 s

[20:36:21] Error in plugin 'gulp-jscs'

Message:

```
Mixed spaces and tabs found at client/app/admin/admin.controller.js :

 3 |  'logger',

 4 |  function(logger) {

 5 |     var vm = this;
```

--------^

```
 6 |    vm.title = 'Admin';

 7 |
```

Expected indentation of 6 characters at client/app/admin/admin.controller.js :

```
 3 |  'logger',

 4 |  function(logger) {

 5 |     var vm = this;
```

--------------^

```
 6 |    vm.title = 'Admin';

 7 |
```

Thanks,

From:  flavordaaave
Reply-To:  flavordaaave/ionic-better-structure
Date:  Monday, 4 January 2016 at 5:33 PM
To:  flavordaaave/ionic-better-structure
Cc:  Sharad Gupta
Subject:  Re: [ionic-better-structure] JSCS doesn't output formatting errors (#3)

Could you give me a JS example? I just did a basic test by removing the semicolon in line 12 of the dash.controller.jsfile and gulp vet is correctly showing me the error:
[13:01:04] Starting 'vet'...
[13:01:04] Analyzing source with JSHint and JSCS

src/app/dash/dash.controller.js
  line 12  col 22  Missing semicolon.  (W033)

  ⚠  1 warning

[13:01:06] Finished 'vet' after 2.06 s

**Comment by davidruisinger** [comment]
For some reasons JSCS was not working with the version 3 I had in my package.json file. I now "downgraded" to v2 and now it seems to be working. I just updated the repository to v 1.1.1 which solves the problem.
