### ISSUE TITLE
src/lib folder doesn't exists

### ISSUE THREAD

**Issue by jackulti** [flavordaaave/ionic-better-structure#4]
I don't see lib folder inside src folder, when ionic serve, I got many errors. Please tell me what's happened?

**Comment by davidruisinger** [comment]
Have you run the commands:

```
$ npm install
$ bower install
```

as described in the "How to use this project" section?

**Comment by jackulti** [comment]
Hi @flavordaaave,

Thanks for quickly response!

When I run `bower install`, I got `bower_components` folder inside root directory. It will work when I copy that folder and paste into `src` folder and rename it to `lib`.

I must do it manually?

**Comment by davidruisinger** [comment]
No, normally this is already defined in the `.bowerrc` file:
https://github.com/flavordaaave/ionic-better-structure/blob/master/.bowerrc

Could you check what your's looks like?

**Comment by jackulti** [comment]
Awww, my fault, I missed some files with `.` prefix when I copy and paste, thanks so much for your support :), I will close this issue.

**Comment by davidruisinger** [comment]
Glad you figured this out. :ok_hand:
