### ISSUE TITLE
Adding Sass

### ISSUE THREAD

**Issue by gabalicious** [flavordaaave/ionic-better-structure#7]
After adding Sass with this command '$ ionic setup sass', using gulp build or ionic build ios creates a project with a white screen.  In Xcode the JS folder and index.html file is missing.  Am I doing something wrong?

**Comment by davidruisinger** [comment]
You don't need to run `ionic setup sass` since this project is already configured to use sass as of default. (see `src/app/styles/ionic.app.scss`)
